### ISSUE TITLE
Use proper event syntax

### ISSUE THREAD

**Issue by Robbepop** [rossbulat/ink-nft#10]
I think it is important that this tutorial series stays up to date.
We introduced special event syntax some time ago and I think it would be perfectly fine to be included into this guide instead of the old work around for it.

**Comment by rossbulat** [comment]
> I think it is important that this tutorial series stays up to date.
> We introduced special event syntax some time ago and I think it would be perfectly fine to be included into this guide instead of the old work around for it.

Do you have any resources to point to outlining the special event syntax?

**Comment by Robbepop** [comment]
https://github.com/paritytech/ink/tree/master/examples/lang/events

**Comment by rossbulat** [comment]
Thank you. Oh yes, that is much nicer syntax. I will amend the tutorial and articles shortly to reflect.

**Comment by rossbulat** [comment]
I have made the changes in #11  and will amend the tutorials before merging.
