### ISSUE TITLE
Recommendation to host blog series as markdown on GH

### ISSUE THREAD

**Issue by lsaether** [rossbulat/ink-nft#3]
As I review the blog, it would be much easier to suggest changes being able to reference line numbers or even by submitting a PR. I would recommend hosting your blog series in GH to allow for external contributions and to easily allow it to keep it up to date. 

This doesn't mean you cannot post to Medium, since I agree shareability is easier there. But to do both and mention that the tech is still early and to refer to GH for the most up-to-date version.

**Comment by rossbulat** [comment]
That definitely makes sense, I plan to do so once the deployment phase has been documented and published.

From there, like you say, we can refer to a Github version for future updates as the module builds up.

**Comment by rossbulat** [comment]
The tutorial is now in Markdown format, closing.
