### ISSUE TITLE
[Blog] Use Owner as example of storage

### ISSUE THREAD

**Issue by lsaether** [rossbulat/ink-nft#6]
You currently use `AccountId` as the name of the storage field in the example, but `Owner` would be better aligned with the solidity comparison.

**Comment by rossbulat** [comment]
Where in the code can `AccountId` be replaced with `Owner`? I have only used AccountId as a type,  I was unaware there was an `Owner` type.

**Comment by lsaether** [comment]
I'm referring to this block of code from the first blog post 
```
// Ink
struct NFToken {
   AccountID: owner: storage::Value<AccountId>,
   approvals: storage::HashMap<u64, AccountId>,
}

// Solidity
address owner;
mapping (uint64 => address) approvals;
```
The line `AccountID: owner: storage::Value<AccountId>` should be changed to `owner: storage::Value<AccountId>`. You are correct there is not `Owner` type.

**Comment by rossbulat** [comment]
Ah understood. Thank you for pointing out! Fixed
