### ISSUE TITLE
invocations of env.caller() and env.println()

### ISSUE THREAD

**Issue by lsaether** [rossbulat/ink-nft#7]
https://github.com/rossbulat/ink-nft/blob/ce7f24ba1da7104955cb97c3aba1db5746b28111/src/lib.rs#L62

In a few places you use `env::caller()` or `env::println()` which should be `env.caller()` or `env.println()`, one place I've shown above but there are more places that should also be found and corrected.

**Comment by rossbulat** [comment]
Ok, I made the switch, there were no issues testing `env.caller()`, used in deploy and pub(external) functions. 

`env.println()` however is giving an error running cargo test *if we do not explicitly import it*:

<img width="590" alt="Screenshot 2019-05-08 at 17 25 22" src="https://user-images.githubusercontent.com/13929023/57361112-b1a6dc80-71b6-11e9-9a95-ebc83ec5bd4d.png">

However when we do, it compiles fine:
```
use ink_core::{
    env::{self, println, AccountId, Balance},
   ...
}
```
